spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xhs?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 开启驼峰命名方式 user_name 自动转成 java 实体类中的 userName
    map-underscore-to-camel-case: true
#配置分页插件pagehelper
pagehelper:
  auto-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    com:
      example:
        xhs:
          dao: DEBUG

xhs:
  staticDir: D:\360安全浏览器下载\springbootdemo\springbootdemo\src\main\resources\static\
